
INSERT INTO TestApp.TestQuestions (category, question, option1, option2, option3, option4, right_answer) VALUES
('Java', 'What is the default value of a boolean variable?', 'true', 'false', 'null', 'undefined', 'false'),
('Java', 'Which of the following is not a valid data type in Java?', 'int', 'float', 'double', 'real', 'real'),
('Java', 'What is the size of an int in Java?', '2 bytes', '4 bytes', '8 bytes', '16 bytes', '4 bytes'),
('Java', 'Which method is used to find the length of a string in Java?', 'length()', 'getLength()', 'size()', 'length', 'length()'),
('Java', 'Which keyword is used to prevent a class from being subclassed?', 'final', 'static', 'private', 'public', 'final'),
('Java', 'Which operator is used to compare two objects in Java?', '==', 'equals()', 'equalsIgnoreCase()', 'compareTo()', 'equals()'),
('Java', 'What is the parent class of all Java classes?', 'Object', 'String', 'Serializable', 'Cloneable', 'Object'),
('Java', 'What does the Java keyword "this" refer to?', 'The current object', 'The previous object', 'A static variable', 'A constructor', 'The current object'),
('Java', 'What is the output of the following code? System.out.println(1+2+"3");', '123', '33', '6', '12', '33'),
('Java', 'Which of the following is used to handle exceptions in Java?', 'try-catch', 'throw-catch', 'try-throw', 'error-catch', 'try-catch'),
('Java', 'Which of the following is not a valid access modifier in Java?', 'private', 'protected', 'public', 'secure', 'secure'),
('Java', 'Which of the following is a valid method signature in Java?', 'void main()', 'public static void main()', 'void static main()', 'static void main()', 'public static void main()'),
('Java', 'Which of the following is true about the final keyword?', 'It can be used for variables, methods, and classes', 'It can only be used for variables', 'It can only be used for methods', 'It can only be used for classes', 'It can be used for variables, methods, and classes'),
('Java', 'Which of the following methods is used to start a thread in Java?', 'start()', 'run()', 'begin()', 'execute()', 'start()'),
('Java', 'Which interface does a class need to implement to become a thread in Java?', 'Runnable', 'Threadable', 'Executor', 'RunnableThread', 'Runnable'),
('Java', 'What is the default value of an integer variable in Java?', '0', '1', 'null', 'undefined', '0'),
('Java', 'What is the size of a float in Java?', '4 bytes', '8 bytes', '2 bytes', '16 bytes', '4 bytes'),
('Java', 'What is the purpose of the hashCode() method in Java?', 'It returns the memory address of an object', 'It provides a unique identifier for an object', 'It compares two objects', 'It checks if an object is null', 'It provides a unique identifier for an object'),
('Java', 'What does the term "polymorphism" refer to in Java?', 'Overloading methods', 'Overriding methods', 'Both overloading and overriding', 'Static method invocation', 'Both overloading and overriding'),
('Java', 'Which method is used to stop a thread in Java?', 'stop()', 'halt()', 'end()', 'terminate()', 'stop()'),
('Java', 'Which of the following classes are part of the Java Collections Framework?', 'ArrayList', 'Vector', 'LinkedList', 'All of the above', 'All of the above'),
('Java', 'What is the purpose of the synchronized keyword in Java?', 'To make a method thread-safe', 'To prevent method overloading', 'To create a new thread', 'To prevent method overriding', 'To make a method thread-safe'),
('Java', 'Which of the following is a wrapper class for the primitive type boolean?', 'Boolean', 'Character', 'Byte', 'Integer', 'Boolean'),
('Java', 'Which of the following is not a valid loop in Java?', 'for', 'while', 'do-while', 'each', 'each'),
('Java', 'What is the size of a double in Java?', '8 bytes', '4 bytes', '16 bytes', '2 bytes', '8 bytes'),
('Java', 'Which of the following is used to create an object in Java?', 'new', 'create', 'object', 'init', 'new'),
('Java', 'Which keyword is used to inherit a class in Java?', 'extends', 'implements', 'super', 'this', 'extends'),
('Java', 'Which of the following is a valid data type in Java?', 'int', 'decimal', 'number', 'longint', 'int'),
('Java', 'Which method is used to compare two strings in Java?', 'equals()', '==', 'compare()', 'compareTo()', 'equals()'),
('Java', 'What is the default value of an array element in Java?', 'null', '0', 'undefined', 'empty', 'null'),
('Java', 'Which of the following is true about an abstract class in Java?', 'It can have abstract and non-abstract methods', 'It can have only abstract methods', 'It can’t have constructors', 'It can have no methods', 'It can have abstract and non-abstract methods'),
('Java', 'Which of the following is a correct way to declare a method in Java?', 'void methodName()', 'methodName()', 'void methodName{}', 'method methodName()', 'void methodName()'),
('Java', 'Which of the following is the correct way to define a constant in Java?', 'final int x = 5;', 'int x = final 5;', 'int final x = 5;', 'const int x = 5;', 'final int x = 5;'),
('Java', 'Which of the following is used to terminate the current method in Java?', 'break', 'continue', 'return', 'exit', 'return'),
('Java', 'Which of the following collections are thread-safe in Java?', 'Vector', 'ArrayList', 'HashSet', 'TreeMap', 'Vector'),
('Java', 'What does JVM stand for?', 'Java Virtual Machine', 'Java Variable Machine', 'Java Virtual Method', 'Java Verified Machine', 'Java Virtual Machine'),
('Java', 'Which of the following is used to handle errors in Java?', 'Error class', 'Throwable class', 'Exception class', 'Error and Exception class', 'Error and Exception class'),
('Java', 'Which of the following keywords is used to create a subclass in Java?', 'extends', 'implements', 'inherits', 'subclass', 'extends'),
('Java', 'Which of the following is a valid statement for method overloading in Java?', 'Methods can have the same name but different parameters', 'Methods can have the same name and same parameters', 'Methods must have different names', 'Methods must be static', 'Methods can have the same name but different parameters'),
('Java', 'Which method is used to check if a string is empty in Java?', 'isEmpty()', 'empty()', 'hasText()', 'isNull()', 'isEmpty()'),
('Java', 'Which method is used to remove an element from an ArrayList?', 'remove()', 'delete()', 'removeElement()', 'clear()', 'remove()'),
('Java', 'What is the output of the following code? System.out.println("abc".charAt(1));', 'b', 'a', 'c', 'bc', 'b'),
('Java', 'Which of the following is used for managing dependencies in Java projects?', 'Maven', 'Gradle', 'Ant', 'All of the above', 'All of the above'),
('Java', 'Which of the following is not a valid exception class in Java?', 'IOException', 'FileNotFoundException', 'SQLException', 'InvalidException', 'InvalidException'),
('Java', 'What is the correct way to initialize an array in Java?', 'int[] arr = new int[5];', 'int arr[] = new int[5];', 'int[] arr = new int[5];', 'All of the above', 'All of the above'),
('Java', 'Which method is used to get the current system time in Java?', 'System.currentTimeMillis()', 'System.getTime()', 'System.current()', 'Time.get()', 'System.currentTimeMillis()'),
('Java', 'Which of the following are primitive data types in Java?', 'int', 'String', 'Object', 'Array', 'int'),
('Java', 'Which of the following is true about static methods in Java?', 'They belong to the class, not the instance', 'They can only be called from the same class', 'They can access instance variables', 'They can be overridden', 'They belong to the class, not the instance');
SELECT * FROM TestApp.TestQuestions;